export const START_PAGE_ENG: any = {
  btnBack: 'Back',
  btnSearch: 'Search',
  inputPlaceHolder: 'Input city',
  infoForUserAboutCurrentLetter: 'Enter the city with the letter',
  popupName: 'Name',
  popupLat: 'Lat',
  popupLong: 'Long',
  mapSatelite: 'Map satelite',
  mapView: 'Map view',
  emptyByUser: `You haven't entered any city yet`,
  emptyByComp: `Still empty`,
  columnUserTitle: 'You have entered the following cities:',
  columnCompTitle: 'Player has entered the following cities:',
  warningMessage1: `It seems that the name of this city has already been. Let's try another one`,
  warningMessage2: `You entered the city with the wrong letter. Try again using the letter `,
  warningMessage3: `Something went wrong. `,
  warningMessage4: `Check the spelling of the city name`,
  warningMessage5: `Game Over`,
  warningMessage6: `Your number of points is`,
  timerTitle: 'Timer',
  scoreTitle: 'Score',
  textTip: 'Change the keyboard layout'
}

export const START_PAGE_RUS: any = {
  btnBack: 'В меню',
  btnSearch: 'Поиск',
  inputPlaceHolder: 'Введите город',
  infoForUserAboutCurrentLetter: 'Введите город на букву',
  popupName: 'Название',
  popupLat: 'Широта',
  popupLong: 'Долгота',
  mapSatelite: 'Спутник',
  mapView: 'Схема',
  emptyByUser: 'Вы пока не ввели ни одного города',
  emptyByComp: 'Пока тут пусто. Поэтому минутка рекламы: "Продам гараж по очень хорошей цене"',
  columnUserTitle: 'Вы ввели следующие города:',
  columnCompTitle: 'Игрок ввел следующие города:',
  warningMessage1: 'Кажется, название этого города уже было. Давайте попробуем другой',
  warningMessage2: 'Вы ввели город на неверную букву. Попробуйте ещё раз, используя букву ',
  warningMessage3: 'Что-то пошло не так. ',
  warningMessage4: '- точно верно написали город?',
  warningMessage5: 'Игра завершена',
  warningMessage6: 'Ваше количество очков:',
  timerTitle: 'Таймер',
  scoreTitle: 'Очки',
  textTip: 'Измените раскладку'
}
