export const START_PAGE_ENG: any = {
  btnBack: 'Back',
  btnSearch: 'Search',
  inputPlaceHolder: 'Input city',
  infoForUserAboutCurrentLetter: 'Enter the city with the letter',
  popupName: 'Name',
  popupLat: 'Lat',
  popupLong: 'Long',
  mapSatelite: 'Map satelite',
  mapView: 'Map view',
  emptyByUser: `You haven't entered any city yet`,
  emptyByComp: `Still empty`,
  columnUserTitle: 'You have entered the following cities:',
  columnCompTitle: 'Player has entered the following cities:',
}

export const START_PAGE_RUS: any = {
  btnBack: 'В меню',
  btnSearch: 'Поиск',
  inputPlaceHolder: 'Введите город',
  infoForUserAboutCurrentLetter: 'Введите город на букву',
  popupName: 'Название',
  popupLat: 'Широта',
  popupLong: 'Долгота',
  mapSatelite: 'Спутник',
  mapView: 'Схема',
  emptyByUser: 'Вы пока не ввели ни одного города',
  emptyByComp: 'Пока тут пусто. Поэтому минутка рекламы: "Продам гараж по очень хорошей цене"',
  columnUserTitle: 'Вы ввели следующие города:',
  columnCompTitle: 'Игрок ввел следующие города:',
}
